Revert "[BZ-1072679] manage NoClassDefFoundError as a ClassNotFoundException raising a compilation error when it occurs"
This reverts commit 8126339ccd261bb9e9d319f09737b5a9a57bf0a7.